version: '3'

services:
  postgres:
    image: postgres:14

    # Permite conexões de qualquer endereço IP
    command:
      - /bin/sh
      - -c
      - echo "host all all 0.0.0.0/0 trust" >> /etc/postgresql/14/main/pg_hba.conf && echo "listen_addresses='*'" >> /etc/postgresql/14/main/postgresql.conf

    # Compartilha o diretório /var/lib/postgresql/data com a máquina local
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data:/db_sql

  pgadmin:
    image: dpage/pgadmin4

    # Configura o cliente para usar o PostgreSQL na porta 5432
    environment:
      PGADMIN_DEFAULT_DATABASE: postgres
      PGADMIN_DEFAULT_USERNAME: postgres
      PGADMIN_DEFAULT_PASSWORD: postgres

    # Expoe a porta 4321 para acesso em redes externas
    ports:
      - 4321:80
